(function(){
const clone=x=>JSON.parse(JSON.stringify(x)),id=()=>crypto.randomUUID();
const seed={products:[],customers:[],invoices:[],moves:[],settings:[{id:'settings',owner_id:'owner',business_name:'Safari Farm & Hatchery',gstin:'19FJHPB6409M1ZU',phone:'7063482623',email:'rifatsahin000@gmail.com',address:'Baranagar Danga, Sujapur, Malda [W.B]',bank_name:'State Bank of India',account_name:'Mukrema Bibi',account_number:'32944542308',ifsc:'SBIN0006810',branch:'Sujapur'}]};
let db;try{db=JSON.parse(localStorage.safari_farm_offline)||clone(seed)}catch{db=clone(seed)}const save=()=>localStorage.safari_farm_offline=JSON.stringify(db);
api=async function(path,opt={}){const method=opt.method||'GET',body=opt.body?JSON.parse(opt.body):null;
if(path==='rpc/sf_adjust_stock'){let p=db.products.find(x=>x.id===body.p_product);if(!p)throw Error('Product not found');p.stock_qty=+p.stock_qty+body.p_change;db.moves.unshift({id:id(),product_id:p.id,qty_change:body.p_change,reason:body.p_reason,created_at:new Date().toISOString()});save();return}
if(path==='rpc/sf_issue_invoice'){let c={id:id(),...body.p_customer};db.customers.push(c);let number=`SFH/${new Date().getFullYear()}/${String(db.invoices.length+1).padStart(4,'0')}`,items=body.p_items;for(const x of items)if(x.product_id){let p=db.products.find(y=>y.id===x.product_id);if(!p||+p.stock_qty<+x.qty)throw Error('Insufficient stock: '+x.name);p.stock_qty-=+x.qty;db.moves.unshift({id:id(),product_id:p.id,qty_change:-x.qty,reason:'Invoice '+number,created_at:new Date().toISOString()})}let base=items.reduce((a,x)=>a+x.qty*x.rate,0),gst=items.reduce((a,x)=>a+x.qty*x.rate*x.gst/100,0);db.invoices.unshift({id:id(),invoice_no:number,invoice_date:body.p_invoice.invoice_date,invoice_type:body.p_invoice.invoice_type,customer_name:c.name,status:'issued',grand_total:base+gst+(+body.p_invoice.freight||0),created_at:new Date().toISOString(),_items:items});save();return}
if(path==='rpc/sf_cancel_invoice'){let inv=db.invoices.find(x=>x.id===body.p_invoice);if(!inv||inv.status!=='issued')throw Error('Invoice already cancelled');for(const x of inv._items||[])if(x.product_id){let p=db.products.find(y=>y.id===x.product_id);p.stock_qty+=+x.qty;db.moves.unshift({id:id(),product_id:p.id,qty_change:+x.qty,reason:'Cancelled '+inv.invoice_no,created_at:new Date().toISOString()})}inv.status='cancelled';save();return}
let table=path.split('?')[0];if(table==='sf_stock_moves')return db.moves.map(x=>({...x,sf_products:{name:db.products.find(p=>p.id===x.product_id)?.name||''}}));let key={sf_products:'products',sf_customers:'customers',sf_invoices:'invoices',sf_settings:'settings'}[table];if(!key)throw Error('Unsupported operation');if(method==='GET')return clone(db[key]);if(method==='POST'){let row={id:id(),...body};db[key].push(row);save();return[row]}if(method==='PATCH'){let match=path.match(/id=eq\.([^&]+)/),row=db[key].find(x=>x.id===match?.[1]);if(!row)throw Error('Record not found');Object.assign(row,body);save();return[row]}}
user={id:'owner'};token='offline';document.querySelector('#loginForm').onsubmit=e=>{e.preventDefault();start()};
window.exportSafariBackup=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='safari-farm-backup.json';a.click()};
start();
})();
