-- Safari Farm & Hatchery — complete idempotent Supabase migration
create extension if not exists pgcrypto;

create table if not exists public.farm_settings(id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid(), business_name text default 'Safari Farm & Hatchery', address text, gstin text, phone text, email text, state text, bank_name text, account_name text, account_number text, ifsc text, branch text, upi text, logo_url text, low_stock_level numeric default 10, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.products(id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid(), name text not null, description text, hsn_sac text, unit text default 'Nos', rate numeric(14,2) default 0, gst_rate numeric(6,2) default 0, stock_qty numeric(14,3) default 0, low_stock_level numeric(14,3) default 10, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.customers(id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid(), customer_type text default 'NON-GST' check(customer_type in ('GST','NON-GST')), name text not null, phone text, email text, gstin text, address text, state text, district text, pincode text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.invoices(id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid(), invoice_no text, invoice_type text default 'TAX INVOICE', process_no text, enquiry_no text, ref_no text, invoice_date date default current_date, valid_till date, customer_id uuid references public.customers(id) on delete restrict, customer_name text, customer_type text, customer_gstin text, customer_phone text, customer_address text, customer_state text, customer_district text, customer_pincode text, subtotal numeric(14,2) default 0, tax_total numeric(14,2) default 0, freight numeric(14,2) default 0, grand_total numeric(14,2) default 0, notes text, status text default 'ISSUED' check(status in ('DRAFT','ISSUED','CANCELLED')), cancelled_at timestamptz, cancel_reason text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.invoice_items(id uuid primary key default gen_random_uuid(), invoice_id uuid not null references public.invoices(id) on delete cascade, product_id uuid references public.products(id) on delete restrict, description text not null, hsn_sac text, unit text, quantity numeric(14,3) not null check(quantity>0), rate numeric(14,2) not null, gst_rate numeric(6,2) default 0, taxable_amount numeric(14,2), gst_amount numeric(14,2), line_total numeric(14,2), created_at timestamptz default now());
create table if not exists public.stock_adjustments(id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid(), product_id uuid not null references public.products(id) on delete restrict, invoice_id uuid references public.invoices(id) on delete set null, quantity_change numeric(14,3) not null, balance_after numeric(14,3) not null, reason text not null, created_at timestamptz default now());

-- Preserve older installations by adding any missing columns.
alter table public.farm_settings add column if not exists owner_id uuid default auth.uid(), add column if not exists bank_name text, add column if not exists account_name text, add column if not exists account_number text, add column if not exists ifsc text, add column if not exists branch text, add column if not exists upi text, add column if not exists logo_url text, add column if not exists low_stock_level numeric default 10;
alter table public.products add column if not exists owner_id uuid default auth.uid(), add column if not exists description text, add column if not exists hsn_sac text, add column if not exists unit text default 'Nos', add column if not exists rate numeric(14,2) default 0, add column if not exists gst_rate numeric(6,2) default 0, add column if not exists stock_qty numeric(14,3) default 0, add column if not exists low_stock_level numeric default 10, add column if not exists updated_at timestamptz default now();
alter table public.customers add column if not exists owner_id uuid default auth.uid(), add column if not exists customer_type text default 'NON-GST', add column if not exists state text, add column if not exists district text, add column if not exists pincode text;
alter table public.invoices add column if not exists owner_id uuid default auth.uid(), add column if not exists invoice_type text default 'TAX INVOICE', add column if not exists process_no text, add column if not exists enquiry_no text, add column if not exists valid_till date, add column if not exists ref_no text, add column if not exists freight numeric(14,2) default 0, add column if not exists status text default 'ISSUED', add column if not exists cancel_reason text, add column if not exists cancelled_at timestamptz;
alter table public.invoices add column if not exists customer_name text, add column if not exists customer_type text, add column if not exists customer_gstin text, add column if not exists customer_phone text, add column if not exists customer_address text, add column if not exists customer_state text, add column if not exists customer_district text, add column if not exists customer_pincode text, add column if not exists subtotal numeric(14,2) default 0, add column if not exists tax_total numeric(14,2) default 0, add column if not exists grand_total numeric(14,2) default 0, add column if not exists notes text, add column if not exists updated_at timestamptz default now();
alter table public.invoice_items add column if not exists taxable_amount numeric(14,2), add column if not exists gst_amount numeric(14,2), add column if not exists line_total numeric(14,2);
alter table public.stock_adjustments add column if not exists owner_id uuid default auth.uid(), add column if not exists invoice_id uuid references public.invoices(id) on delete set null, add column if not exists balance_after numeric(14,3), add column if not exists reason text;

create unique index if not exists invoices_owner_number_uq on public.invoices(owner_id,invoice_no);
create index if not exists products_owner_name_idx on public.products(owner_id,name);
create index if not exists adjustments_product_date_idx on public.stock_adjustments(product_id,created_at desc);

alter table public.farm_settings enable row level security; alter table public.products enable row level security; alter table public.customers enable row level security; alter table public.invoices enable row level security; alter table public.invoice_items enable row level security; alter table public.stock_adjustments enable row level security;
do $$ declare t text; begin foreach t in array array['farm_settings','products','customers','invoices','stock_adjustments'] loop execute format('drop policy if exists owner_all on public.%I',t); execute format('create policy owner_all on public.%I for all to authenticated using (owner_id=auth.uid()) with check (owner_id=auth.uid())',t); end loop; end $$;
drop policy if exists owner_invoice_items on public.invoice_items; create policy owner_invoice_items on public.invoice_items for all to authenticated using(exists(select 1 from public.invoices i where i.id=invoice_id and i.owner_id=auth.uid())) with check(exists(select 1 from public.invoices i where i.id=invoice_id and i.owner_id=auth.uid()));

create or replace function public.adjust_stock(p_product_id uuid,p_quantity_change numeric,p_reason text) returns public.products language plpgsql security invoker as $$ declare p public.products; begin select * into p from public.products where id=p_product_id and owner_id=auth.uid() for update; if not found then raise exception 'Product not found'; end if; if p.stock_qty+p_quantity_change<0 then raise exception 'Stock cannot become negative'; end if; update public.products set stock_qty=stock_qty+p_quantity_change,updated_at=now() where id=p_product_id returning * into p; insert into public.stock_adjustments(owner_id,product_id,quantity_change,balance_after,reason) values(auth.uid(),p_product_id,p_quantity_change,p.stock_qty,coalesce(nullif(p_reason,''),'Manual adjustment')); return p; end $$;

create or replace function public.save_invoice(p_invoice_id uuid,p_customer_id uuid,p_invoice_type text,p_invoice_date date,p_valid_till date,p_ref_no text,p_freight numeric,p_notes text,p_items jsonb) returns public.invoices language plpgsql security invoker as $$
declare inv public.invoices; c public.customers; it jsonb; p public.products; old record; seq int; sub numeric:=0; tax numeric:=0; qty numeric; rate_v numeric; gst_v numeric;
begin
 select * into c from public.customers where id=p_customer_id and owner_id=auth.uid(); if not found then raise exception 'Customer not found'; end if;
 if p_invoice_id is not null then
  select * into inv from public.invoices where id=p_invoice_id and owner_id=auth.uid() and status='ISSUED' for update; if not found then raise exception 'Invoice cannot be edited'; end if;
  for old in select * from public.invoice_items where invoice_id=inv.id loop update public.products set stock_qty=stock_qty+old.quantity where id=old.product_id; insert into public.stock_adjustments(owner_id,product_id,invoice_id,quantity_change,balance_after,reason) select auth.uid(),id,inv.id,old.quantity,stock_qty,'Invoice edit: previous quantity restored' from public.products where id=old.product_id; end loop; delete from public.invoice_items where invoice_id=inv.id;
 else select coalesce(max((regexp_match(invoice_no,'([0-9]+)$'))[1]::int),0)+1 into seq from public.invoices where owner_id=auth.uid(); insert into public.invoices(owner_id,invoice_no,process_no,enquiry_no,status) values(auth.uid(),'SFH-'||to_char(current_date,'YYYY')||'-'||lpad(seq::text,4,'0'),'PROC-'||to_char(now(),'YYMMDD')||'-'||lpad(seq::text,4,'0'),'ENQ-'||to_char(now(),'YYMM')||'-'||lpad(seq::text,4,'0'),'ISSUED') returning * into inv; end if;
 for it in select * from jsonb_array_elements(p_items) loop qty=(it->>'quantity')::numeric; rate_v=(it->>'rate')::numeric; gst_v=coalesce((it->>'gst_rate')::numeric,0); select * into p from public.products where id=(it->>'product_id')::uuid and owner_id=auth.uid() for update; if not found or p.stock_qty<qty then raise exception 'Insufficient stock for %',coalesce(p.name,'product'); end if; update public.products set stock_qty=stock_qty-qty,updated_at=now() where id=p.id returning * into p; insert into public.invoice_items(invoice_id,product_id,description,hsn_sac,unit,quantity,rate,gst_rate,taxable_amount,gst_amount,line_total) values(inv.id,p.id,coalesce(it->>'description',p.name),coalesce(it->>'hsn_sac',p.hsn_sac),coalesce(it->>'unit',p.unit),qty,rate_v,gst_v,qty*rate_v,qty*rate_v*gst_v/100,qty*rate_v*(1+gst_v/100)); insert into public.stock_adjustments(owner_id,product_id,invoice_id,quantity_change,balance_after,reason) values(auth.uid(),p.id,inv.id,-qty,p.stock_qty,'Invoice '||inv.invoice_no); sub=sub+qty*rate_v; tax=tax+qty*rate_v*gst_v/100; end loop;
 update public.invoices set invoice_type=p_invoice_type,invoice_date=p_invoice_date,valid_till=p_valid_till,ref_no=p_ref_no,freight=coalesce(p_freight,0),notes=p_notes,customer_id=c.id,customer_name=c.name,customer_type=c.customer_type,customer_gstin=c.gstin,customer_phone=c.phone,customer_address=c.address,customer_state=c.state,customer_district=c.district,customer_pincode=c.pincode,subtotal=sub,tax_total=tax,grand_total=sub+tax+coalesce(p_freight,0),updated_at=now() where id=inv.id returning * into inv; return inv;
end $$;

create or replace function public.cancel_invoice(p_invoice_id uuid,p_reason text) returns public.invoices language plpgsql security invoker as $$ declare inv public.invoices; it record; bal numeric; begin select * into inv from public.invoices where id=p_invoice_id and owner_id=auth.uid() and status='ISSUED' for update; if not found then raise exception 'Invoice cannot be cancelled'; end if; for it in select * from public.invoice_items where invoice_id=inv.id loop update public.products set stock_qty=stock_qty+it.quantity,updated_at=now() where id=it.product_id returning stock_qty into bal; insert into public.stock_adjustments(owner_id,product_id,invoice_id,quantity_change,balance_after,reason) values(auth.uid(),it.product_id,inv.id,it.quantity,bal,'Cancelled '||inv.invoice_no); end loop; update public.invoices set status='CANCELLED',cancelled_at=now(),cancel_reason=p_reason,updated_at=now() where id=inv.id returning * into inv; return inv; end $$;

grant execute on function public.adjust_stock(uuid,numeric,text) to authenticated; grant execute on function public.save_invoice(uuid,uuid,text,date,date,text,numeric,text,jsonb) to authenticated; grant execute on function public.cancel_invoice(uuid,text) to authenticated;

-- One-time ownership adoption for rows created by an older single-user version.
create or replace function public.claim_legacy_data() returns void language plpgsql security definer set search_path=public as $$ begin if auth.uid() is null then raise exception 'Sign in required'; end if; update farm_settings set owner_id=auth.uid() where owner_id is null; update products set owner_id=auth.uid() where owner_id is null; update customers set owner_id=auth.uid() where owner_id is null; update invoices set owner_id=auth.uid() where owner_id is null; update stock_adjustments set owner_id=auth.uid() where owner_id is null; end $$;
revoke all on function public.claim_legacy_data() from public; grant execute on function public.claim_legacy_data() to authenticated;
