-- Safari Farm fresh schema. Safe beside older tables because every table starts with sf_.
create extension if not exists pgcrypto;
create table if not exists public.sf_settings(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,business_name text not null default 'Safari Farm & Hatchery',gstin text,phone text,email text,address text,bank_name text,account_name text,account_number text,ifsc text,branch text,unique(owner_id));
create table if not exists public.sf_products(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,name text not null,description text default '',hsn text default '',unit text not null default 'Nos',rate numeric(14,2) not null default 0,gst numeric(6,2) not null default 0,stock_qty numeric(14,2) not null default 0,low_stock numeric(14,2) not null default 5,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.sf_customers(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,customer_type text not null default 'non_gst',name text not null,phone text,email text,gstin text,address text,state text,city text,pincode text,created_at timestamptz not null default now());
create table if not exists public.sf_invoices(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,invoice_no text not null,process_no text not null,enquiry_no text not null,invoice_type text not null,invoice_date date not null,valid_till date,reference_no text,customer_id uuid references public.sf_customers(id),customer_name text not null,customer_snapshot jsonb not null,subtotal numeric(14,2),gst_total numeric(14,2),freight numeric(14,2),grand_total numeric(14,2),notes text,status text not null default 'issued',cancel_reason text,created_at timestamptz not null default now(),unique(owner_id,invoice_no));
create table if not exists public.sf_invoice_items(id uuid primary key default gen_random_uuid(),invoice_id uuid not null references public.sf_invoices(id) on delete cascade,owner_id uuid not null references auth.users(id) on delete cascade,product_id uuid references public.sf_products(id),item_kind text not null,name text not null,hsn text,unit text,qty numeric(14,2) not null,rate numeric(14,2) not null,gst numeric(6,2) not null,amount numeric(14,2) not null);
create table if not exists public.sf_stock_moves(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,product_id uuid not null references public.sf_products(id),invoice_id uuid references public.sf_invoices(id),qty_change numeric(14,2) not null,reason text not null,created_at timestamptz not null default now());
alter table public.sf_settings enable row level security; alter table public.sf_products enable row level security; alter table public.sf_customers enable row level security; alter table public.sf_invoices enable row level security; alter table public.sf_invoice_items enable row level security; alter table public.sf_stock_moves enable row level security;
do $$ declare t text; begin foreach t in array array['sf_settings','sf_products','sf_customers','sf_invoices','sf_invoice_items','sf_stock_moves'] loop execute format('drop policy if exists owner_all on public.%I',t); execute format('create policy owner_all on public.%I for all using (owner_id=auth.uid()) with check (owner_id=auth.uid())',t); end loop; end $$;
create or replace function public.sf_adjust_stock(p_product uuid,p_change numeric,p_reason text) returns void language plpgsql security invoker as $$ begin if p_change=0 then raise exception 'Change cannot be zero'; end if; update public.sf_products set stock_qty=stock_qty+p_change where id=p_product and owner_id=auth.uid(); if not found then raise exception 'Product not found'; end if; insert into public.sf_stock_moves(owner_id,product_id,qty_change,reason) values(auth.uid(),p_product,p_change,p_reason); end $$;
create or replace function public.sf_issue_invoice(p_customer jsonb,p_invoice jsonb,p_items jsonb) returns uuid language plpgsql security invoker as $$ declare uid uuid:=auth.uid(); cid uuid;iid uuid;seq int;ino text;pno text;eno text;it jsonb;pid uuid;q numeric;r numeric;g numeric;sub numeric:=0;gt numeric:=0; begin if uid is null then raise exception 'Please sign in again'; end if; insert into public.sf_customers(owner_id,customer_type,name,phone,email,gstin,address,state,city,pincode) values(uid,coalesce(p_customer->>'customer_type','non_gst'),p_customer->>'name',p_customer->>'phone',p_customer->>'email',p_customer->>'gstin',p_customer->>'address',p_customer->>'state',p_customer->>'city',p_customer->>'pincode') returning id into cid; select count(*)+1 into seq from public.sf_invoices where owner_id=uid and extract(year from invoice_date)=extract(year from current_date); ino:=format('SFH/%s/%s',extract(year from current_date)::int,lpad(seq::text,4,'0'));pno:=format('PF/%s/%s',extract(year from current_date)::int,lpad(seq::text,4,'0'));eno:=format('ENQ/SFH-%s-%s',extract(year from current_date)::int,lpad(seq::text,4,'0')); for it in select * from jsonb_array_elements(p_items) loop q:=(it->>'qty')::numeric;r:=(it->>'rate')::numeric;g:=(it->>'gst')::numeric;sub:=sub+q*r;gt:=gt+q*r*(1+g/100); end loop;gt:=gt+coalesce((p_invoice->>'freight')::numeric,0); insert into public.sf_invoices(owner_id,invoice_no,process_no,enquiry_no,invoice_type,invoice_date,valid_till,reference_no,customer_id,customer_name,customer_snapshot,subtotal,gst_total,freight,grand_total,notes) values(uid,ino,pno,eno,p_invoice->>'invoice_type',(p_invoice->>'invoice_date')::date,nullif(p_invoice->>'valid_till','')::date,p_invoice->>'reference_no',cid,p_customer->>'name',p_customer,sub,gt-sub-coalesce((p_invoice->>'freight')::numeric,0),coalesce((p_invoice->>'freight')::numeric,0),gt,p_invoice->>'notes') returning id into iid; for it in select * from jsonb_array_elements(p_items) loop pid:=nullif(it->>'product_id','')::uuid;q:=(it->>'qty')::numeric;r:=(it->>'rate')::numeric;g:=(it->>'gst')::numeric;if pid is not null then update public.sf_products set stock_qty=stock_qty-q where id=pid and owner_id=uid and stock_qty>=q;if not found then raise exception 'Insufficient stock for %',it->>'name';end if;insert into public.sf_stock_moves(owner_id,product_id,invoice_id,qty_change,reason) values(uid,pid,iid,-q,'Invoice '||ino);end if;insert into public.sf_invoice_items(invoice_id,owner_id,product_id,item_kind,name,hsn,unit,qty,rate,gst,amount) values(iid,uid,pid,coalesce(it->>'kind','custom'),it->>'name',it->>'hsn',it->>'unit',q,r,g,q*r*(1+g/100));end loop;return iid;end $$;
create or replace function public.sf_cancel_invoice(p_invoice uuid,p_reason text) returns void language plpgsql security invoker as $$ declare uid uuid:=auth.uid();it record;begin if not exists(select 1 from public.sf_invoices where id=p_invoice and owner_id=uid and status='issued') then raise exception 'Invoice not found or already cancelled';end if;for it in select product_id,qty from public.sf_invoice_items where invoice_id=p_invoice and owner_id=uid and product_id is not null loop update public.sf_products set stock_qty=stock_qty+it.qty where id=it.product_id and owner_id=uid;insert into public.sf_stock_moves(owner_id,product_id,invoice_id,qty_change,reason) values(uid,it.product_id,p_invoice,it.qty,'Cancelled invoice: '||p_reason);end loop;update public.sf_invoices set status='cancelled',cancel_reason=p_reason where id=p_invoice and owner_id=uid;end $$;
grant execute on function public.sf_adjust_stock(uuid,numeric,text) to authenticated;grant execute on function public.sf_issue_invoice(jsonb,jsonb,jsonb) to authenticated;grant execute on function public.sf_cancel_invoice(uuid,text) to authenticated;
notify pgrst,'reload schema';
