-- Clean isolated schema. Safe with older tables because every object uses sfh_ prefix.
create extension if not exists pgcrypto;
create table if not exists public.sfh_customers(id uuid primary key default gen_random_uuid(),name text not null,customer_type text not null default 'Non-GST' check(customer_type in('GST','Non-GST')),phone text,email text,gstin text,address text,state text,state_code text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.sfh_products(id uuid primary key default gen_random_uuid(),name text not null,sku text not null unique,hsn text,unit text not null default 'Nos',sale_price numeric(12,2) not null default 0,gst_rate numeric(5,2) not null default 0,current_stock numeric(14,3) not null default 0,low_stock_threshold numeric(14,3) not null default 0,active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.sfh_invoices(id uuid primary key default gen_random_uuid(),invoice_type text not null default 'Proforma Invoice',invoice_no text unique,process_no text unique,inquiry_no text unique,customer_id uuid references public.sfh_customers(id),customer_snapshot jsonb,invoice_date date default current_date,subtotal numeric(14,2) default 0,tax_total numeric(14,2) default 0,grand_total numeric(14,2) default 0,amount_paid numeric(14,2) default 0,payment_status text default 'Unpaid' check(payment_status in('Paid','Partial','Unpaid')),notes text,created_at timestamptz default now());
create table if not exists public.sfh_invoice_items(id uuid primary key default gen_random_uuid(),invoice_id uuid not null references public.sfh_invoices(id) on delete cascade,product_id uuid references public.sfh_products(id),description text not null,hsn text,quantity numeric(14,3) not null check(quantity>0),unit text,rate numeric(14,2) not null,discount numeric(5,2) default 0,gst_rate numeric(5,2) default 0,tax_amount numeric(14,2) default 0,line_total numeric(14,2) not null);
create table if not exists public.sfh_stock_movements(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.sfh_products(id),movement_type text not null check(movement_type in('ADD','REMOVE','SALE','ADJUSTMENT')),quantity numeric(14,3) not null,balance_after numeric(14,3) not null,reason text,invoice_id uuid references public.sfh_invoices(id),created_at timestamptz default now());
create table if not exists public.sfh_settings(id uuid primary key default gen_random_uuid(),business_name text default 'SAFARI FARM & HATCHERY',tagline text,address text,phone text,email text,gstin text,bank_name text,account_name text,account_no text,ifsc text,branch text,upi_id text,logo_url text,signature_url text,notes text,terms text,updated_at timestamptz default now());
insert into public.sfh_settings(business_name) select 'SAFARI FARM & HATCHERY' where not exists(select 1 from public.sfh_settings);
create sequence if not exists public.sfh_invoice_seq; create sequence if not exists public.sfh_process_seq; create sequence if not exists public.sfh_inquiry_seq;
create or replace function public.sfh_number_for(prefix text,seq regclass) returns text language plpgsql security definer set search_path=public as $$ declare n bigint; begin n:=nextval(seq);return prefix||'-'||extract(year from current_date)::int||'-'||lpad(n::text,4,'0');end $$;
create or replace function public.sfh_adjust_stock(p_product_id uuid,p_quantity numeric,p_reason text default 'Manual adjustment') returns void language plpgsql security definer set search_path=public as $$ declare b numeric;begin update sfh_products set current_stock=current_stock+p_quantity,updated_at=now() where id=p_product_id and current_stock+p_quantity>=0 returning current_stock into b;if b is null then raise exception 'Not enough stock or product not found';end if;insert into sfh_stock_movements(product_id,movement_type,quantity,balance_after,reason)values(p_product_id,case when p_quantity>=0 then 'ADD' else 'REMOVE' end,p_quantity,b,p_reason);end $$;
create or replace function public.sfh_create_invoice(p_invoice jsonb,p_items jsonb) returns uuid language plpgsql security definer set search_path=public as $$ declare nid uuid:=gen_random_uuid();it jsonb;b numeric;begin insert into sfh_invoices(id,invoice_no,process_no,inquiry_no,customer_id,invoice_date,subtotal,tax_total,grand_total,amount_paid,payment_status,notes)values(nid,sfh_number_for('SFH','sfh_invoice_seq'),sfh_number_for('PR','sfh_process_seq'),sfh_number_for('INQ','sfh_inquiry_seq'),(p_invoice->>'customer_id')::uuid,(p_invoice->>'invoice_date')::date,(p_invoice->>'subtotal')::numeric,(p_invoice->>'tax_total')::numeric,(p_invoice->>'grand_total')::numeric,(p_invoice->>'amount_paid')::numeric,p_invoice->>'payment_status',p_invoice->>'notes');for it in select * from jsonb_array_elements(p_items) loop update sfh_products set current_stock=current_stock-(it->>'quantity')::numeric where id=(it->>'product_id')::uuid and current_stock>=(it->>'quantity')::numeric returning current_stock into b;if b is null then raise exception 'Insufficient stock for %',it->>'description';end if;insert into sfh_invoice_items(invoice_id,product_id,description,hsn,quantity,unit,rate,discount,gst_rate,tax_amount,line_total)values(nid,(it->>'product_id')::uuid,it->>'description',it->>'hsn',(it->>'quantity')::numeric,it->>'unit',(it->>'rate')::numeric,(it->>'discount')::numeric,(it->>'gst_rate')::numeric,(it->>'tax_amount')::numeric,(it->>'line_total')::numeric);insert into sfh_stock_movements(product_id,movement_type,quantity,balance_after,reason,invoice_id)values((it->>'product_id')::uuid,'SALE',-(it->>'quantity')::numeric,b,'Invoice sale',nid);end loop;return nid;end $$;
alter table public.sfh_customers enable row level security;alter table public.sfh_products enable row level security;alter table public.sfh_invoices enable row level security;alter table public.sfh_invoice_items enable row level security;alter table public.sfh_stock_movements enable row level security;alter table public.sfh_settings enable row level security;
create policy "sfh anon customers" on public.sfh_customers for all to anon using(true) with check(true);create policy "sfh anon products" on public.sfh_products for all to anon using(true) with check(true);create policy "sfh anon invoices" on public.sfh_invoices for all to anon using(true) with check(true);create policy "sfh anon items" on public.sfh_invoice_items for all to anon using(true) with check(true);create policy "sfh anon stock" on public.sfh_stock_movements for all to anon using(true) with check(true);create policy "sfh anon settings" on public.sfh_settings for all to anon using(true) with check(true);
grant execute on function public.sfh_adjust_stock(uuid,numeric,text) to anon,authenticated;grant execute on function public.sfh_create_invoice(jsonb,jsonb) to anon,authenticated;
